"""queue leases schedules webhooks

Revision ID: a270c776cab7
Revises: 4bfa179c3a31
Create Date: 2026-08-27 16:51:04.660224
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a270c776cab7'
down_revision = '4bfa179c3a31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('workflow', sa.String(length=64), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('copilot_model', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_job_id', sa.String(length=32), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_workflow'), ['workflow'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_status'), ['status'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_owner', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
        # server_default, not just a Python-side default: existing rows need a
        # value at ALTER time, and SQLite refuses a NOT NULL column without one.
        batch_op.add_column(
            sa.Column('attempt', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('webhook_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('schedule_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_lease_expires_at'), ['lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_lease_owner'), ['lease_owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_lease_owner'))
        batch_op.drop_index(batch_op.f('ix_jobs_lease_expires_at'))
        batch_op.drop_column('schedule_id')
        batch_op.drop_column('webhook_url')
        batch_op.drop_column('attempt')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('lease_owner')

    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_job_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_workflow'))
        batch_op.drop_index(batch_op.f('ix_schedules_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_schedules_enabled'))

    op.drop_table('schedules')
    # ### end Alembic commands ###
