/**
 * Which agent naturally runs after this one.
 *
 * The hub already knows this and was not being asked. Every agent declares the
 * artifact it reads and the artifact it writes, and every workflow declares the
 * order its stages run in — so "what comes after the test designer" has a real
 * answer derived from the registry, rather than the user having to remember the
 * pipeline and pick from a flat list of every agent onboarded.
 *
 * Two sources, in order of confidence:
 *
 *  1. **A workflow says so.** A stage whose `depends_on` names this agent's
 *     stage is its declared successor. A workflow with no dependencies at all
 *     is a plain sequence, so the next entry in the list is the successor.
 *  2. **The artifacts line up.** An agent whose `input_artifact` is exactly what
 *     this one writes can consume its output, whether or not any workflow has
 *     put the two together yet.
 *
 * Nothing is inferred beyond that. A suggestion the user does not recognise is
 * worse than no suggestion, so a guess is never dressed up as a pipeline.
 */
import type { HubAgent, HubCatalog, HubWorkflow } from '@/lib/hub-api';
import { displayAgentName } from '@/lib/agent-name';

export interface AgentSuggestion {
  id: string;
  name: string;
  /** Shown on the chip's tooltip — why this one is being offered. */
  reason: string;
}

/** A workflow entry carries `depends_on` at runtime; the list type omits it. */
type WorkflowStage = HubWorkflow['agents'][number] & { depends_on?: string[] | string };

/**
 * Artifact paths from a field that may be a string, a list, or neither.
 *
 * These come from YAML frontmatter written by hand or generated by the Workflow
 * Builder, so the type is whatever the author typed. Coercing rather than
 * trusting keeps a malformed definition to a missing suggestion instead of a
 * blank page.
 */
function artifactPaths(...values: unknown[]): string[] {
  const out: string[] = [];
  for (const value of values) {
    if (typeof value === 'string') {
      const trimmed = value.trim();
      if (trimmed) out.push(trimmed);
    } else if (Array.isArray(value)) {
      for (const item of value) {
        if (typeof item === 'string' && item.trim()) out.push(item.trim());
      }
    }
  }
  return out;
}

function dependsOn(stage: WorkflowStage): string[] {
  const raw = stage.depends_on;
  if (!raw) return [];
  return Array.isArray(raw) ? raw.map(String) : [String(raw)];
}

function successorsFromWorkflow(
  workflow: HubWorkflow,
  agentId: string,
): { id: string; reason: string }[] {
  const stages = (workflow.agents ?? []) as WorkflowStage[];
  const here = stages.findIndex((s) => s.id === agentId);
  if (here === -1) return [];

  const declaresDependencies = stages.some((s) => dependsOn(s).length > 0);

  if (!declaresDependencies) {
    // No `depends_on` anywhere means the list order *is* the order — which is
    // exactly how the runner treats it.
    const next = stages[here + 1];
    return next ? [{ id: next.id, reason: `next in ${workflow.name}` }] : [];
  }

  const stageName = stages[here].stage;
  return stages
    .filter((s) => dependsOn(s).includes(stageName))
    .map((s) => ({ id: s.id, reason: `runs after ${stageName} in ${workflow.name}` }));
}

/**
 * Agents that can sensibly run after `agentId`, best first.
 *
 * Returns an empty list when nothing in the registry connects to this agent —
 * which is a true answer, not a failure.
 */
export function nextAgents(
  agentId: string | null | undefined,
  catalog: HubCatalog | null | undefined,
  limit = 4,
): AgentSuggestion[] {
  if (!agentId || !catalog) return [];

  const agents = catalog.agents ?? [];
  const current = agents.find((a) => a.id === agentId);
  if (!current) return [];

  const byId = new Map<string, HubAgent>(agents.map((a) => [a.id, a]));
  const ordered: { id: string; reason: string }[] = [];

  for (const workflow of catalog.workflows ?? []) {
    ordered.push(...successorsFromWorkflow(workflow, agentId));
  }

  // Artifact chaining: whoever reads what this one writes.
  //
  // A fan-in agent declares several inputs, so match against all of them. The
  // registry normalises the shape, but this reads it defensively anyway: the
  // hub is a directory of files anyone can edit, so its contents are data of
  // unknown shape, and a suggestion chip is never worth crashing the console
  // for. `(x || '').trim()` did exactly that when an author wrote a YAML list.
  const writes = artifactPaths(current.output_artifact, current.output_artifacts);
  const written = writes.find((path) => path && path !== 'workspace');
  if (written) {
    for (const candidate of agents) {
      if (candidate.id === agentId) continue;
      const reads = artifactPaths(candidate.input_artifact, candidate.input_artifacts);
      if (reads.includes(written)) {
        ordered.push({ id: candidate.id, reason: `reads ${written}` });
      }
    }
  }

  const seen = new Set<string>([agentId]);
  const out: AgentSuggestion[] = [];
  for (const { id, reason } of ordered) {
    if (seen.has(id)) continue;
    const agent = byId.get(id);
    if (!agent) continue; // named by a workflow but not onboarded
    seen.add(id);
    out.push({ id, name: displayAgentName(id, agent.name), reason });
    if (out.length >= limit) break;
  }
  return out;
}
